// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// AuthConfig defines details of a authentication type.
public struct AuthConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The type of authentication configured.
  public var authType: AuthType = AuthType()

  /// List containing additional auth configs.
  public var additionalVariables: [ConfigVariable] = []

  /// Supported auth types.
  public var type: TypeOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AuthConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuthConfig().with { $0.authType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let authType = CodingKeys(stringValue: "authType")
    static let userPassword = CodingKeys(stringValue: "userPassword")
    static let oauth2JwtBearer = CodingKeys(stringValue: "oauth2JwtBearer")
    static let oauth2ClientCredentials = CodingKeys(stringValue: "oauth2ClientCredentials")
    static let sshPublicKey = CodingKeys(stringValue: "sshPublicKey")
    static let additionalVariables = CodingKeys(stringValue: "additionalVariables")

    static let _knownKeys: Set<Swift.String> = [
      "authType",
      "userPassword",
      "oauth2JwtBearer",
      "oauth2ClientCredentials",
      "sshPublicKey",
      "additionalVariables",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(AuthType.self, forKey: .authType) {
      self.authType = value
    }
    if let value = try container.decodeIfPresent(
      [ConfigVariable].self, forKey: .additionalVariables)
    {
      self.additionalVariables = value
    }

    var type: TypeOneOf? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let userPassword = try container.decodeIfPresent(
      AuthConfig.UserPassword.self, forKey: .userPassword)
    {
      try typeCheckAndSet(.userPassword(userPassword))
    }
    if let oauth2JwtBearer = try container.decodeIfPresent(
      AuthConfig.Oauth2JwtBearer.self, forKey: .oauth2JwtBearer)
    {
      try typeCheckAndSet(.oauth2JwtBearer(oauth2JwtBearer))
    }
    if let oauth2ClientCredentials = try container.decodeIfPresent(
      AuthConfig.Oauth2ClientCredentials.self, forKey: .oauth2ClientCredentials)
    {
      try typeCheckAndSet(.oauth2ClientCredentials(oauth2ClientCredentials))
    }
    if let sshPublicKey = try container.decodeIfPresent(
      AuthConfig.SshPublicKey.self, forKey: .sshPublicKey)
    {
      try typeCheckAndSet(.sshPublicKey(sshPublicKey))
    }
    self.type = type
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.authType, forKey: .authType)
    try container.encode(self.additionalVariables, forKey: .additionalVariables)

    if let choice = self.type {
      switch choice {
      case .userPassword(let value):
        try container.encode(value, forKey: .userPassword)
      case .oauth2JwtBearer(let value):
        try container.encode(value, forKey: .oauth2JwtBearer)
      case .oauth2ClientCredentials(let value):
        try container.encode(value, forKey: .oauth2ClientCredentials)
      case .sshPublicKey(let value):
        try container.encode(value, forKey: .sshPublicKey)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Parameters to support Username and Password Authentication.
  public struct UserPassword: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Username.
    public var username: Swift.String = Swift.String()

    /// Secret version reference containing the password.
    public var password: Secret? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `UserPassword`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UserPassword().with { $0.username = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let username = CodingKeys(stringValue: "username")
      static let password = CodingKeys(stringValue: "password")

      static let _knownKeys: Set<Swift.String> = [
        "username",
        "password",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .username) {
        self.username = value
      }
      self.password = try container.decodeIfPresent(Secret.self, forKey: .password)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.username, forKey: .username)
      try container.encodeIfPresent(self.password, forKey: .password)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.AuthConfig.UserPassword"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Parameters to support JSON Web Token (JWT) Profile for Oauth 2.0
  /// Authorization Grant based authentication.
  /// See https://tools.ietf.org/html/rfc7523 for more details.
  public struct Oauth2JwtBearer: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Secret version reference containing a PKCS#8 PEM-encoded private
    /// key associated with the Client Certificate. This private key will be
    /// used to sign JWTs used for the jwt-bearer authorization grant.
    /// Specified in the form as: `projects/*/secrets/*/versions/*`.
    public var clientKey: Secret? = nil

    /// JwtClaims providers fields to generate the token.
    public var jwtClaims: AuthConfig.Oauth2JwtBearer.JwtClaims? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Oauth2JwtBearer`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Oauth2JwtBearer().with { $0.clientKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientKey = CodingKeys(stringValue: "clientKey")
      static let jwtClaims = CodingKeys(stringValue: "jwtClaims")

      static let _knownKeys: Set<Swift.String> = [
        "clientKey",
        "jwtClaims",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.clientKey = try container.decodeIfPresent(Secret.self, forKey: .clientKey)
      self.jwtClaims = try container.decodeIfPresent(
        AuthConfig.Oauth2JwtBearer.JwtClaims.self, forKey: .jwtClaims)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.clientKey, forKey: .clientKey)
      try container.encodeIfPresent(self.jwtClaims, forKey: .jwtClaims)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// JWT claims used for the jwt-bearer authorization grant.
    public struct JwtClaims: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Value for the "iss" claim.
      public var issuer: Swift.String = Swift.String()

      /// Value for the "sub" claim.
      public var subject: Swift.String = Swift.String()

      /// Value for the "aud" claim.
      public var audience: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `JwtClaims`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = JwtClaims().with { $0.issuer = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let issuer = CodingKeys(stringValue: "issuer")
        static let subject = CodingKeys(stringValue: "subject")
        static let audience = CodingKeys(stringValue: "audience")

        static let _knownKeys: Set<Swift.String> = [
          "issuer",
          "subject",
          "audience",
        ]
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .issuer) {
          self.issuer = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .subject) {
          self.subject = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .audience) {
          self.audience = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.issuer, forKey: .issuer)
        try container.encode(self.subject, forKey: .subject)
        try container.encode(self.audience, forKey: .audience)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.connectors.v1.AuthConfig.Oauth2JwtBearer.JwtClaims"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.AuthConfig.Oauth2JwtBearer"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Parameters to support Oauth 2.0 Client Credentials Grant Authentication.
  /// See https://tools.ietf.org/html/rfc6749#section-1.3.4 for more details.
  public struct Oauth2ClientCredentials: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The client identifier.
    public var clientId: Swift.String = Swift.String()

    /// Secret version reference containing the client secret.
    public var clientSecret: Secret? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Oauth2ClientCredentials`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Oauth2ClientCredentials().with { $0.clientId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientId = CodingKeys(stringValue: "clientId")
      static let clientSecret = CodingKeys(stringValue: "clientSecret")

      static let _knownKeys: Set<Swift.String> = [
        "clientId",
        "clientSecret",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientId) {
        self.clientId = value
      }
      self.clientSecret = try container.decodeIfPresent(Secret.self, forKey: .clientSecret)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.clientId, forKey: .clientId)
      try container.encodeIfPresent(self.clientSecret, forKey: .clientSecret)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.AuthConfig.Oauth2ClientCredentials"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Parameters to support Ssh public key Authentication.
  public struct SshPublicKey: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The user account used to authenticate.
    public var username: Swift.String = Swift.String()

    /// SSH Client Cert. It should contain both public and private key.
    public var sshClientCert: Secret? = nil

    /// Format of SSH Client cert.
    public var certType: Swift.String = Swift.String()

    /// Password (passphrase) for ssh client certificate if it has one.
    public var sshClientCertPass: Secret? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SshPublicKey`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SshPublicKey().with { $0.username = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let username = CodingKeys(stringValue: "username")
      static let sshClientCert = CodingKeys(stringValue: "sshClientCert")
      static let certType = CodingKeys(stringValue: "certType")
      static let sshClientCertPass = CodingKeys(stringValue: "sshClientCertPass")

      static let _knownKeys: Set<Swift.String> = [
        "username",
        "sshClientCert",
        "certType",
        "sshClientCertPass",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .username) {
        self.username = value
      }
      self.sshClientCert = try container.decodeIfPresent(Secret.self, forKey: .sshClientCert)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .certType) {
        self.certType = value
      }
      self.sshClientCertPass = try container.decodeIfPresent(
        Secret.self, forKey: .sshClientCertPass)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.username, forKey: .username)
      try container.encodeIfPresent(self.sshClientCert, forKey: .sshClientCert)
      try container.encode(self.certType, forKey: .certType)
      try container.encodeIfPresent(self.sshClientCertPass, forKey: .sshClientCertPass)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.AuthConfig.SshPublicKey"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Supported auth types.
  public enum TypeOneOf: Codable, Equatable, Sendable {
    /// UserPassword.
    indirect case userPassword(AuthConfig.UserPassword)
    /// Oauth2JwtBearer.
    indirect case oauth2JwtBearer(AuthConfig.Oauth2JwtBearer)
    /// Oauth2ClientCredentials.
    indirect case oauth2ClientCredentials(AuthConfig.Oauth2ClientCredentials)
    /// SSH Public Key.
    indirect case sshPublicKey(AuthConfig.SshPublicKey)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.AuthConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
