// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// This configuration captures the details required to render an authorization
/// link for the OAuth Authorization Code Flow.
public struct AuthorizationCodeLink: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The base URI the user must click to trigger the authorization code login
  /// flow.
  public var uri: Swift.String = Swift.String()

  /// The scopes for which the user will authorize GCP Connectors on the
  /// connector data source.
  public var scopes: [Swift.String] = []

  /// The client ID assigned to the GCP Connectors OAuth app for the connector
  /// data source.
  public var clientId: Swift.String = Swift.String()

  /// Whether to enable PKCE for the auth code flow.
  public var enablePkce: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AuthorizationCodeLink`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuthorizationCodeLink().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let uri = CodingKeys(stringValue: "uri")
    static let scopes = CodingKeys(stringValue: "scopes")
    static let clientId = CodingKeys(stringValue: "clientId")
    static let enablePkce = CodingKeys(stringValue: "enablePkce")

    static let _knownKeys: Set<Swift.String> = [
      "uri",
      "scopes",
      "clientId",
      "enablePkce",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      self.uri = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .scopes) {
      self.scopes = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientId) {
      self.clientId = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enablePkce) {
      self.enablePkce = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.uri, forKey: .uri)
    try container.encode(self.scopes, forKey: .scopes)
    try container.encode(self.clientId, forKey: .clientId)
    try container.encode(self.enablePkce, forKey: .enablePkce)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `AuthorizationCodeLink`: `"type.googleapis.com/google.cloud.connectors.v1.AuthorizationCodeLink"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.AuthorizationCodeLink"
  }

  /// Initialize an instance of `AuthorizationCodeLink` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.connectors.v1.AuthorizationCodeLink"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AuthorizationCodeLink` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
