// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// AuthType defines different authentication types.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum AuthType: Codable, Equatable, Hashable, Sendable {
  /// Authentication type not specified.
  case unspecified
  /// Username and Password Authentication.
  case userPassword
  /// JSON Web Token (JWT) Profile for Oauth 2.0
  /// Authorization Grant based authentication
  case oauth2JwtBearer
  /// Oauth 2.0 Client Credentials Grant Authentication
  case oauth2ClientCredentials
  /// SSH Public Key Authentication
  case sshPublicKey
  /// Oauth 2.0 Authorization Code Flow
  case oauth2AuthCodeFlow
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .userPassword: return 1
    case .oauth2JwtBearer: return 2
    case .oauth2ClientCredentials: return 3
    case .sshPublicKey: return 4
    case .oauth2AuthCodeFlow: return 5
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "AUTH_TYPE_UNSPECIFIED"
    case .userPassword: return "USER_PASSWORD"
    case .oauth2JwtBearer: return "OAUTH2_JWT_BEARER"
    case .oauth2ClientCredentials: return "OAUTH2_CLIENT_CREDENTIALS"
    case .sshPublicKey: return "SSH_PUBLIC_KEY"
    case .oauth2AuthCodeFlow: return "OAUTH2_AUTH_CODE_FLOW"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AuthType/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "AUTH_TYPE_UNSPECIFIED": self = .unspecified
    case "USER_PASSWORD": self = .userPassword
    case "OAUTH2_JWT_BEARER": self = .oauth2JwtBearer
    case "OAUTH2_CLIENT_CREDENTIALS": self = .oauth2ClientCredentials
    case "SSH_PUBLIC_KEY": self = .sshPublicKey
    case "OAUTH2_AUTH_CODE_FLOW": self = .oauth2AuthCodeFlow
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AuthType/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .userPassword
    case 2: self = .oauth2JwtBearer
    case 3: self = .oauth2ClientCredentials
    case 4: self = .sshPublicKey
    case 5: self = .oauth2AuthCodeFlow
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("AUTH_TYPE_UNSPECIFIED")
    case .userPassword: return try container.encode("USER_PASSWORD")
    case .oauth2JwtBearer: return try container.encode("OAUTH2_JWT_BEARER")
    case .oauth2ClientCredentials: return try container.encode("OAUTH2_CLIENT_CREDENTIALS")
    case .sshPublicKey: return try container.encode("SSH_PUBLIC_KEY")
    case .oauth2AuthCodeFlow: return try container.encode("OAUTH2_AUTH_CODE_FLOW")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
