// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ConfigVariableTemplate provides metadata about a `ConfigVariable` that is
/// used in a Connection.
public struct ConfigVariableTemplate: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Key of the config variable.
  public var key: Swift.String = Swift.String()

  /// Type of the parameter: string, int, bool etc.
  /// consider custom type for the benefit for the validation.
  public var valueType: ConfigVariableTemplate.ValueType = ConfigVariableTemplate.ValueType()

  /// Display name of the parameter.
  public var displayName: Swift.String = Swift.String()

  /// Description.
  public var description: Swift.String = Swift.String()

  /// Regular expression in RE2 syntax used for validating the `value` of a
  /// `ConfigVariable`.
  public var validationRegex: Swift.String = Swift.String()

  /// Flag represents that this `ConfigVariable` must be provided for a
  /// connection.
  public var `required`: Swift.Bool = Swift.Bool()

  /// Role grant configuration for the config variable.
  public var roleGrant: RoleGrant? = nil

  /// Enum options. To be populated if `ValueType` is `ENUM`
  public var enumOptions: [EnumOption] = []

  /// Authorization code link options. To be populated if `ValueType` is
  /// `AUTHORIZATION_CODE`
  public var authorizationCodeLink: AuthorizationCodeLink? = nil

  /// State of the config variable.
  public var state: ConfigVariableTemplate.State = ConfigVariableTemplate.State()

  /// Indicates if current template is part of advanced settings
  public var isAdvanced: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ConfigVariableTemplate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConfigVariableTemplate().with { $0.key = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let key = CodingKeys(stringValue: "key")
    static let valueType = CodingKeys(stringValue: "valueType")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let validationRegex = CodingKeys(stringValue: "validationRegex")
    static let `required` = CodingKeys(stringValue: "required")
    static let roleGrant = CodingKeys(stringValue: "roleGrant")
    static let enumOptions = CodingKeys(stringValue: "enumOptions")
    static let authorizationCodeLink = CodingKeys(stringValue: "authorizationCodeLink")
    static let state = CodingKeys(stringValue: "state")
    static let isAdvanced = CodingKeys(stringValue: "isAdvanced")

    static let _knownKeys: Set<Swift.String> = [
      "key",
      "valueType",
      "displayName",
      "description",
      "validationRegex",
      "required",
      "roleGrant",
      "enumOptions",
      "authorizationCodeLink",
      "state",
      "isAdvanced",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .key) {
      self.key = value
    }
    if let value = try container.decodeIfPresent(
      ConfigVariableTemplate.ValueType.self, forKey: .valueType)
    {
      self.valueType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .validationRegex) {
      self.validationRegex = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .`required`) {
      self.`required` = value
    }
    self.roleGrant = try container.decodeIfPresent(RoleGrant.self, forKey: .roleGrant)
    if let value = try container.decodeIfPresent([EnumOption].self, forKey: .enumOptions) {
      self.enumOptions = value
    }
    self.authorizationCodeLink = try container.decodeIfPresent(
      AuthorizationCodeLink.self, forKey: .authorizationCodeLink)
    if let value = try container.decodeIfPresent(ConfigVariableTemplate.State.self, forKey: .state)
    {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isAdvanced) {
      self.isAdvanced = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.key, forKey: .key)
    try container.encode(self.valueType, forKey: .valueType)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.validationRegex, forKey: .validationRegex)
    try container.encode(self.`required`, forKey: .`required`)
    try container.encodeIfPresent(self.roleGrant, forKey: .roleGrant)
    try container.encode(self.enumOptions, forKey: .enumOptions)
    try container.encodeIfPresent(self.authorizationCodeLink, forKey: .authorizationCodeLink)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.isAdvanced, forKey: .isAdvanced)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// ValueType indicates the data type of the value.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ValueType: Codable, Equatable, Hashable, Sendable {
    /// Value type is not specified.
    case unspecified
    /// Value type is string.
    case string
    /// Value type is integer.
    case int
    /// Value type is boolean.
    case bool
    /// Value type is secret.
    case secret
    /// Value type is enum.
    case `enum`
    /// Value type is authorization code.
    case authorizationCode
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .string: return 1
      case .int: return 2
      case .bool: return 3
      case .secret: return 4
      case .`enum`: return 5
      case .authorizationCode: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VALUE_TYPE_UNSPECIFIED"
      case .string: return "STRING"
      case .int: return "INT"
      case .bool: return "BOOL"
      case .secret: return "SECRET"
      case .`enum`: return "ENUM"
      case .authorizationCode: return "AUTHORIZATION_CODE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ValueType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VALUE_TYPE_UNSPECIFIED": self = .unspecified
      case "STRING": self = .string
      case "INT": self = .int
      case "BOOL": self = .bool
      case "SECRET": self = .secret
      case "ENUM": self = .`enum`
      case "AUTHORIZATION_CODE": self = .authorizationCode
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ValueType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .string
      case 2: self = .int
      case 3: self = .bool
      case 4: self = .secret
      case 5: self = .`enum`
      case 6: self = .authorizationCode
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("VALUE_TYPE_UNSPECIFIED")
      case .string: return try container.encode("STRING")
      case .int: return try container.encode("INT")
      case .bool: return try container.encode("BOOL")
      case .secret: return try container.encode("SECRET")
      case .`enum`: return try container.encode("ENUM")
      case .authorizationCode: return try container.encode("AUTHORIZATION_CODE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Indicates the state of the config variable.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// Status is unspecified.
    case unspecified
    /// Config variable is active
    case active
    /// Config variable is deprecated.
    case deprecated
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .deprecated: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .deprecated: return "DEPRECATED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "DEPRECATED": self = .deprecated
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .deprecated
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .deprecated: return try container.encode("DEPRECATED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.ConfigVariableTemplate"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
