// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Connection represents an instance of connector.
public struct Connection: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Resource name of the Connection.
  /// Format: projects/{project}/locations/{location}/connections/{connection}
  public var name: Swift.String = Swift.String()

  /// Output only. Created time.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Updated time.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Resource labels to represent user-provided metadata.
  /// Refer to cloud documentation on labels for more details.
  /// https://cloud.google.com/compute/docs/labeling-resources
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Description of the resource.
  public var description: Swift.String = Swift.String()

  /// Required. Connector version on which the connection is created.
  /// The format is:
  /// projects/*/locations/*/providers/*/connectors/*/versions/*
  /// Only global location is supported for ConnectorVersion resource.
  public var connectorVersion: Swift.String = Swift.String()

  /// Output only. Current status of the connection.
  public var status: ConnectionStatus? = nil

  /// Optional. Configuration for configuring the connection with an external
  /// system.
  public var configVariables: [ConfigVariable] = []

  /// Optional. Configuration for establishing the connection's authentication
  /// with an external system.
  public var authConfig: AuthConfig? = nil

  /// Optional. Configuration that indicates whether or not the Connection can be
  /// edited.
  public var lockConfig: LockConfig? = nil

  /// Optional. Configuration of the Connector's destination. Only accepted for
  /// Connectors that accepts user defined destination(s).
  public var destinationConfigs: [DestinationConfig] = []

  /// Output only. GCR location where the runtime image is stored.
  /// formatted like: gcr.io/{bucketName}/{imageName}
  public var imageLocation: Swift.String = Swift.String()

  /// Optional. Service account needed for runtime plane to access GCP resources.
  public var serviceAccount: Swift.String = Swift.String()

  /// Output only. The name of the Service Directory service name. Used for
  /// Private Harpoon to resolve the ILB address.
  /// e.g.
  /// "projects/cloud-connectors-e2e-testing/locations/us-central1/namespaces/istio-system/services/istio-ingressgateway-connectors"
  public var serviceDirectory: Swift.String = Swift.String()

  /// Output only. GCR location where the envoy image is stored.
  /// formatted like: gcr.io/{bucketName}/{imageName}
  public var envoyImageLocation: Swift.String = Swift.String()

  /// Optional. Suspended indicates if a user has suspended a connection or not.
  public var suspended: Swift.Bool = Swift.Bool()

  /// Optional. Node configuration for the connection.
  public var nodeConfig: NodeConfig? = nil

  /// Optional. Ssl config of a connection
  public var sslConfig: SslConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Connection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Connection().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let description = CodingKeys(stringValue: "description")
    static let connectorVersion = CodingKeys(stringValue: "connectorVersion")
    static let status = CodingKeys(stringValue: "status")
    static let configVariables = CodingKeys(stringValue: "configVariables")
    static let authConfig = CodingKeys(stringValue: "authConfig")
    static let lockConfig = CodingKeys(stringValue: "lockConfig")
    static let destinationConfigs = CodingKeys(stringValue: "destinationConfigs")
    static let imageLocation = CodingKeys(stringValue: "imageLocation")
    static let serviceAccount = CodingKeys(stringValue: "serviceAccount")
    static let serviceDirectory = CodingKeys(stringValue: "serviceDirectory")
    static let envoyImageLocation = CodingKeys(stringValue: "envoyImageLocation")
    static let suspended = CodingKeys(stringValue: "suspended")
    static let nodeConfig = CodingKeys(stringValue: "nodeConfig")
    static let sslConfig = CodingKeys(stringValue: "sslConfig")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "description",
      "connectorVersion",
      "status",
      "configVariables",
      "authConfig",
      "lockConfig",
      "destinationConfigs",
      "imageLocation",
      "serviceAccount",
      "serviceDirectory",
      "envoyImageLocation",
      "suspended",
      "nodeConfig",
      "sslConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .connectorVersion) {
      self.connectorVersion = value
    }
    self.status = try container.decodeIfPresent(ConnectionStatus.self, forKey: .status)
    if let value = try container.decodeIfPresent([ConfigVariable].self, forKey: .configVariables) {
      self.configVariables = value
    }
    self.authConfig = try container.decodeIfPresent(AuthConfig.self, forKey: .authConfig)
    self.lockConfig = try container.decodeIfPresent(LockConfig.self, forKey: .lockConfig)
    if let value = try container.decodeIfPresent(
      [DestinationConfig].self, forKey: .destinationConfigs)
    {
      self.destinationConfigs = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageLocation) {
      self.imageLocation = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
      self.serviceAccount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceDirectory) {
      self.serviceDirectory = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .envoyImageLocation) {
      self.envoyImageLocation = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .suspended) {
      self.suspended = value
    }
    self.nodeConfig = try container.decodeIfPresent(NodeConfig.self, forKey: .nodeConfig)
    self.sslConfig = try container.decodeIfPresent(SslConfig.self, forKey: .sslConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.connectorVersion, forKey: .connectorVersion)
    try container.encodeIfPresent(self.status, forKey: .status)
    try container.encode(self.configVariables, forKey: .configVariables)
    try container.encodeIfPresent(self.authConfig, forKey: .authConfig)
    try container.encodeIfPresent(self.lockConfig, forKey: .lockConfig)
    try container.encode(self.destinationConfigs, forKey: .destinationConfigs)
    try container.encode(self.imageLocation, forKey: .imageLocation)
    try container.encode(self.serviceAccount, forKey: .serviceAccount)
    try container.encode(self.serviceDirectory, forKey: .serviceDirectory)
    try container.encode(self.envoyImageLocation, forKey: .envoyImageLocation)
    try container.encode(self.suspended, forKey: .suspended)
    try container.encodeIfPresent(self.nodeConfig, forKey: .nodeConfig)
    try container.encodeIfPresent(self.sslConfig, forKey: .sslConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.Connection"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
