// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Connectors indicates a specific connector type, e.x. Salesforce, SAP etc.
public struct Connector: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Resource name of the Connector.
  /// Format:
  /// projects/{project}/locations/{location}/providers/{provider}/connectors/{connector}
  /// Only global location is supported for Connector resource.
  public var name: Swift.String = Swift.String()

  /// Output only. Created time.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Updated time.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Resource labels to represent user-provided metadata.
  /// Refer to cloud documentation on labels for more details.
  /// https://cloud.google.com/compute/docs/labeling-resources
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Link to documentation page.
  public var documentationUri: Swift.String = Swift.String()

  /// Output only. Link to external page.
  public var externalUri: Swift.String = Swift.String()

  /// Output only. Description of the resource.
  public var description: Swift.String = Swift.String()

  /// Output only. Cloud storage location of icons etc consumed by UI.
  public var webAssetsLocation: Swift.String = Swift.String()

  /// Output only. Display name.
  public var displayName: Swift.String = Swift.String()

  /// Output only. Flag to mark the version indicating the launch stage.
  public var launchStage: GoogleCloudConnectorsV1.LaunchStage =
    GoogleCloudConnectorsV1.LaunchStage()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Connector`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Connector().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let documentationUri = CodingKeys(stringValue: "documentationUri")
    static let externalUri = CodingKeys(stringValue: "externalUri")
    static let description = CodingKeys(stringValue: "description")
    static let webAssetsLocation = CodingKeys(stringValue: "webAssetsLocation")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let launchStage = CodingKeys(stringValue: "launchStage")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "documentationUri",
      "externalUri",
      "description",
      "webAssetsLocation",
      "displayName",
      "launchStage",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .documentationUri) {
      self.documentationUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .externalUri) {
      self.externalUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .webAssetsLocation) {
      self.webAssetsLocation = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(
      GoogleCloudConnectorsV1.LaunchStage.self, forKey: .launchStage)
    {
      self.launchStage = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.documentationUri, forKey: .documentationUri)
    try container.encode(self.externalUri, forKey: .externalUri)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.webAssetsLocation, forKey: .webAssetsLocation)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.launchStage, forKey: .launchStage)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.Connector"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
