// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleIAMV1
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Connectors is the interface for managing Connectors.
///
/// @Snippet(path: "ConnectorsQuickstart")
public final class ConnectorsClient: Clients.ConnectorsProtocol, Sendable {
  let inner: any Clients.ConnectorsStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.PollingBackoffPolicy

  /// Creates a new `ConnectorsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ConnectorsStub = try Clients.ConnectorsTransport(options)
    inner = Clients.ConnectorsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ConnectorsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists Connections in a given project and location.
  ///
  /// @Snippet(path: "Connectors_ListConnections")
  public func listConnections(
    request: ListConnectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ListConnectionsResponse {
    try await self.inner.listConnections(request: request, options: options)
  }

  /// Gets details of a single Connection.
  ///
  /// @Snippet(path: "Connectors_GetConnection")
  public func getConnection(
    request: GetConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.Connection {
    try await self.inner.getConnection(request: request, options: options)
  }

  /// Creates a new Connection in a given project and location.
  ///
  /// @Snippet(path: "Connectors_CreateConnection")
  public func createConnection(
    request: CreateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createConnection(request: request, options: options)
  }

  /// Creates a new Connection in a given project and location.
  ///
  /// @Snippet(path: "Connectors_CreateConnection")
  public func createConnectionPollingUntilDone(
    request: CreateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> Connection {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Connection>.State in
      return try op._extractStatus(Connection.self)
    }
    let rawOp = try await self.createConnection(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Connection>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Updates the parameters of a single Connection.
  ///
  /// @Snippet(path: "Connectors_UpdateConnection")
  public func updateConnection(
    request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateConnection(request: request, options: options)
  }

  /// Updates the parameters of a single Connection.
  ///
  /// @Snippet(path: "Connectors_UpdateConnection")
  public func updateConnectionPollingUntilDone(
    request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> Connection {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Connection>.State in
      return try op._extractStatus(Connection.self)
    }
    let rawOp = try await self.updateConnection(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Connection>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Deletes a single Connection.
  ///
  /// @Snippet(path: "Connectors_DeleteConnection")
  public func deleteConnection(
    request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteConnection(request: request, options: options)
  }

  /// Deletes a single Connection.
  ///
  /// @Snippet(path: "Connectors_DeleteConnection")
  public func deleteConnectionPollingUntilDone(
    request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteConnection(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Lists Providers in a given project and location.
  ///
  /// @Snippet(path: "Connectors_ListProviders")
  public func listProviders(
    request: ListProvidersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ListProvidersResponse {
    try await self.inner.listProviders(request: request, options: options)
  }

  /// Gets details of a provider.
  ///
  /// @Snippet(path: "Connectors_GetProvider")
  public func getProvider(
    request: GetProviderRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.Provider {
    try await self.inner.getProvider(request: request, options: options)
  }

  /// Lists Connectors in a given project and location.
  ///
  /// @Snippet(path: "Connectors_ListConnectors")
  public func listConnectors(
    request: ListConnectorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ListConnectorsResponse {
    try await self.inner.listConnectors(request: request, options: options)
  }

  /// Gets details of a single Connector.
  ///
  /// @Snippet(path: "Connectors_GetConnector")
  public func getConnector(
    request: GetConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.Connector {
    try await self.inner.getConnector(request: request, options: options)
  }

  /// Lists Connector Versions in a given project and location.
  ///
  /// @Snippet(path: "Connectors_ListConnectorVersions")
  public func listConnectorVersions(
    request: ListConnectorVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ListConnectorVersionsResponse {
    try await self.inner.listConnectorVersions(request: request, options: options)
  }

  /// Gets details of a single connector version.
  ///
  /// @Snippet(path: "Connectors_GetConnectorVersion")
  public func getConnectorVersion(
    request: GetConnectorVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ConnectorVersion {
    try await self.inner.getConnectorVersion(request: request, options: options)
  }

  /// Gets schema metadata of a connection.
  /// SchemaMetadata is a singleton resource for each connection.
  ///
  /// @Snippet(path: "Connectors_GetConnectionSchemaMetadata")
  public func getConnectionSchemaMetadata(
    request: GetConnectionSchemaMetadataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ConnectionSchemaMetadata {
    try await self.inner.getConnectionSchemaMetadata(request: request, options: options)
  }

  /// Refresh runtime schema of a connection.
  ///
  /// @Snippet(path: "Connectors_RefreshConnectionSchemaMetadata")
  public func refreshConnectionSchemaMetadata(
    request: RefreshConnectionSchemaMetadataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.refreshConnectionSchemaMetadata(request: request, options: options)
  }

  /// Refresh runtime schema of a connection.
  ///
  /// @Snippet(path: "Connectors_RefreshConnectionSchemaMetadata")
  public func refreshConnectionSchemaMetadataPollingUntilDone(
    request: RefreshConnectionSchemaMetadataRequest, options: GoogleGax.RequestOptions
  ) async throws -> ConnectionSchemaMetadata {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ConnectionSchemaMetadata>.State in
      return try op._extractStatus(ConnectionSchemaMetadata.self)
    }
    let rawOp = try await self.refreshConnectionSchemaMetadata(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<ConnectionSchemaMetadata>.State
      in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// List schema of a runtime entities filtered by entity name.
  ///
  /// @Snippet(path: "Connectors_ListRuntimeEntitySchemas")
  public func listRuntimeEntitySchemas(
    request: ListRuntimeEntitySchemasRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ListRuntimeEntitySchemasResponse {
    try await self.inner.listRuntimeEntitySchemas(request: request, options: options)
  }

  /// List schema of a runtime actions filtered by action name.
  ///
  /// @Snippet(path: "Connectors_ListRuntimeActionSchemas")
  public func listRuntimeActionSchemas(
    request: ListRuntimeActionSchemasRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ListRuntimeActionSchemasResponse {
    try await self.inner.listRuntimeActionSchemas(request: request, options: options)
  }

  /// Gets the runtimeConfig of a location.
  /// RuntimeConfig is a singleton resource for each location.
  ///
  /// @Snippet(path: "Connectors_GetRuntimeConfig")
  public func getRuntimeConfig(
    request: GetRuntimeConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.RuntimeConfig {
    try await self.inner.getRuntimeConfig(request: request, options: options)
  }

  /// GetGlobalSettings gets settings of a project.
  /// GlobalSettings is a singleton resource.
  ///
  /// @Snippet(path: "Connectors_GetGlobalSettings")
  public func getGlobalSettings(
    request: GetGlobalSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.Settings {
    try await self.inner.getGlobalSettings(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Connectors_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Connectors_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "Connectors_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "Connectors_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "Connectors_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Lists operations that match the specified filter in the request. If
  /// the server doesn't support this method, it returns `UNIMPLEMENTED`.
  ///
  /// @Snippet(path: "Connectors_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Connectors_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Connectors_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Connectors_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ConnectorsClient`.
  ///
  /// To mock `ConnectorsClient` change your functions to receive
  /// `some ConnectorsProtocol` or `any ConnectorsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ConnectorsProtocol: Sendable {
    /// See `ConnectorsClient.listConnections`.
    func listConnections(
      request: ListConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListConnectionsResponse

    /// See `ConnectorsClient.getConnection`.
    func getConnection(
      request: GetConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.Connection

    /// See `ConnectorsClient.createConnection`.
    func createConnection(
      request: CreateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConnectorsClient.createConnection`.
    func createConnectionPollingUntilDone(
      request: CreateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> Connection

    /// See `ConnectorsClient.updateConnection`.
    func updateConnection(
      request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConnectorsClient.updateConnection`.
    func updateConnectionPollingUntilDone(
      request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> Connection

    /// See `ConnectorsClient.deleteConnection`.
    func deleteConnection(
      request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConnectorsClient.deleteConnection`.
    func deleteConnectionPollingUntilDone(
      request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ConnectorsClient.listProviders`.
    func listProviders(
      request: ListProvidersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListProvidersResponse

    /// See `ConnectorsClient.getProvider`.
    func getProvider(
      request: GetProviderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.Provider

    /// See `ConnectorsClient.listConnectors`.
    func listConnectors(
      request: ListConnectorsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListConnectorsResponse

    /// See `ConnectorsClient.getConnector`.
    func getConnector(
      request: GetConnectorRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.Connector

    /// See `ConnectorsClient.listConnectorVersions`.
    func listConnectorVersions(
      request: ListConnectorVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListConnectorVersionsResponse

    /// See `ConnectorsClient.getConnectorVersion`.
    func getConnectorVersion(
      request: GetConnectorVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ConnectorVersion

    /// See `ConnectorsClient.getConnectionSchemaMetadata`.
    func getConnectionSchemaMetadata(
      request: GetConnectionSchemaMetadataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ConnectionSchemaMetadata

    /// See `ConnectorsClient.refreshConnectionSchemaMetadata`.
    func refreshConnectionSchemaMetadata(
      request: RefreshConnectionSchemaMetadataRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ConnectorsClient.refreshConnectionSchemaMetadata`.
    func refreshConnectionSchemaMetadataPollingUntilDone(
      request: RefreshConnectionSchemaMetadataRequest, options: GoogleGax.RequestOptions
    ) async throws -> ConnectionSchemaMetadata

    /// See `ConnectorsClient.listRuntimeEntitySchemas`.
    func listRuntimeEntitySchemas(
      request: ListRuntimeEntitySchemasRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListRuntimeEntitySchemasResponse

    /// See `ConnectorsClient.listRuntimeActionSchemas`.
    func listRuntimeActionSchemas(
      request: ListRuntimeActionSchemasRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.ListRuntimeActionSchemasResponse

    /// See `ConnectorsClient.getRuntimeConfig`.
    func getRuntimeConfig(
      request: GetRuntimeConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.RuntimeConfig

    /// See `ConnectorsClient.getGlobalSettings`.
    func getGlobalSettings(
      request: GetGlobalSettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudConnectorsV1.Settings

    /// See `ConnectorsClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `ConnectorsClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `ConnectorsClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `ConnectorsClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `ConnectorsClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `ConnectorsClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ConnectorsClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ConnectorsClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ConnectorsProtocol {
  public func listConnections(request: ListConnectionsRequest) async throws
    -> GoogleCloudConnectorsV1.ListConnectionsResponse
  {
    try await self.listConnections(request: request, options: .init())
  }

  public func listConnections(
    request: ListConnectionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ListConnectionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listConnectionsByItems(
    request: ListConnectionsRequest
  ) -> some AsyncSequence<Connection, Swift.Error> & Sendable {
    self.listConnectionsByItems(request: request, options: .init())
  }

  /// Lists Connections in a given project and location.
  ///
  /// @Snippet(path: "Connectors_ListConnections")
  public func listConnectionsByItems(
    request: ListConnectionsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Connection, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudConnectorsV1.ListConnectionsResponse in
      var request = request
      request.pageToken = token
      return try await self.listConnections(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listConnectionsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Connection, Swift.Error> & Sendable {
    let request = ListConnectionsRequest().with {
      $0.parent = parent
    }
    return self.listConnectionsByItems(request: request)
  }

  public func getConnection(request: GetConnectionRequest) async throws
    -> GoogleCloudConnectorsV1.Connection
  {
    try await self.getConnection(request: request, options: .init())
  }

  public func getConnection(
    request: GetConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.Connection {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getConnection(
    name: Swift.String,
  ) async throws -> GoogleCloudConnectorsV1.Connection {
    let request = GetConnectionRequest().with {
      $0.name = name
    }
    return try await self.getConnection(request: request)
  }

  public func createConnection(request: CreateConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createConnection(request: request, options: .init())
  }

  public func createConnection(
    request: CreateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createConnectionPollingUntilDone(request: CreateConnectionRequest) async throws
    -> Connection
  {
    return try await self.createConnectionPollingUntilDone(request: request, options: .init())
  }

  public func createConnectionPollingUntilDone(
    request: CreateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> Connection {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createConnectionPollingUntilDone(
    parent: Swift.String,
    connection: Connection?,
    connectionId: Swift.String,
  ) async throws -> Connection {
    let request = CreateConnectionRequest().with {
      $0.parent = parent
      $0.connection = connection
      $0.connectionId = connectionId
    }
    return try await self.createConnectionPollingUntilDone(request: request)
  }

  public func updateConnection(request: UpdateConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateConnection(request: request, options: .init())
  }

  public func updateConnection(
    request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateConnectionPollingUntilDone(request: UpdateConnectionRequest) async throws
    -> Connection
  {
    return try await self.updateConnectionPollingUntilDone(request: request, options: .init())
  }

  public func updateConnectionPollingUntilDone(
    request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> Connection {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateConnectionPollingUntilDone(
    connection: Connection?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> Connection {
    let request = UpdateConnectionRequest().with {
      $0.connection = connection
      $0.updateMask = updateMask
    }
    return try await self.updateConnectionPollingUntilDone(request: request)
  }

  public func deleteConnection(request: DeleteConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteConnection(request: request, options: .init())
  }

  public func deleteConnection(
    request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteConnectionPollingUntilDone(request: DeleteConnectionRequest) async throws {
    try await self.deleteConnectionPollingUntilDone(request: request, options: .init())
  }

  public func deleteConnectionPollingUntilDone(
    request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteConnectionPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteConnectionRequest().with {
      $0.name = name
    }
    try await self.deleteConnectionPollingUntilDone(request: request)
  }

  public func listProviders(request: ListProvidersRequest) async throws
    -> GoogleCloudConnectorsV1.ListProvidersResponse
  {
    try await self.listProviders(request: request, options: .init())
  }

  public func listProviders(
    request: ListProvidersRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ListProvidersResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listProvidersByItems(
    request: ListProvidersRequest
  ) -> some AsyncSequence<Provider, Swift.Error> & Sendable {
    self.listProvidersByItems(request: request, options: .init())
  }

  /// Lists Providers in a given project and location.
  ///
  /// @Snippet(path: "Connectors_ListProviders")
  public func listProvidersByItems(
    request: ListProvidersRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Provider, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudConnectorsV1.ListProvidersResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listProviders(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listProvidersByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Provider, Swift.Error> & Sendable {
    let request = ListProvidersRequest().with {
      $0.parent = parent
    }
    return self.listProvidersByItems(request: request)
  }

  public func getProvider(request: GetProviderRequest) async throws
    -> GoogleCloudConnectorsV1.Provider
  {
    try await self.getProvider(request: request, options: .init())
  }

  public func getProvider(
    request: GetProviderRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.Provider {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getProvider(
    name: Swift.String,
  ) async throws -> GoogleCloudConnectorsV1.Provider {
    let request = GetProviderRequest().with {
      $0.name = name
    }
    return try await self.getProvider(request: request)
  }

  public func listConnectors(request: ListConnectorsRequest) async throws
    -> GoogleCloudConnectorsV1.ListConnectorsResponse
  {
    try await self.listConnectors(request: request, options: .init())
  }

  public func listConnectors(
    request: ListConnectorsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ListConnectorsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listConnectorsByItems(
    request: ListConnectorsRequest
  ) -> some AsyncSequence<Connector, Swift.Error> & Sendable {
    self.listConnectorsByItems(request: request, options: .init())
  }

  /// Lists Connectors in a given project and location.
  ///
  /// @Snippet(path: "Connectors_ListConnectors")
  public func listConnectorsByItems(
    request: ListConnectorsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Connector, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudConnectorsV1.ListConnectorsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listConnectors(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listConnectorsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Connector, Swift.Error> & Sendable {
    let request = ListConnectorsRequest().with {
      $0.parent = parent
    }
    return self.listConnectorsByItems(request: request)
  }

  public func getConnector(request: GetConnectorRequest) async throws
    -> GoogleCloudConnectorsV1.Connector
  {
    try await self.getConnector(request: request, options: .init())
  }

  public func getConnector(
    request: GetConnectorRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.Connector {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getConnector(
    name: Swift.String,
  ) async throws -> GoogleCloudConnectorsV1.Connector {
    let request = GetConnectorRequest().with {
      $0.name = name
    }
    return try await self.getConnector(request: request)
  }

  public func listConnectorVersions(request: ListConnectorVersionsRequest) async throws
    -> GoogleCloudConnectorsV1.ListConnectorVersionsResponse
  {
    try await self.listConnectorVersions(request: request, options: .init())
  }

  public func listConnectorVersions(
    request: ListConnectorVersionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ListConnectorVersionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listConnectorVersionsByItems(
    request: ListConnectorVersionsRequest
  ) -> some AsyncSequence<ConnectorVersion, Swift.Error> & Sendable {
    self.listConnectorVersionsByItems(request: request, options: .init())
  }

  /// Lists Connector Versions in a given project and location.
  ///
  /// @Snippet(path: "Connectors_ListConnectorVersions")
  public func listConnectorVersionsByItems(
    request: ListConnectorVersionsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ConnectorVersion, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudConnectorsV1.ListConnectorVersionsResponse in
      var request = request
      request.pageToken = token
      return try await self.listConnectorVersions(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listConnectorVersionsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ConnectorVersion, Swift.Error> & Sendable {
    let request = ListConnectorVersionsRequest().with {
      $0.parent = parent
    }
    return self.listConnectorVersionsByItems(request: request)
  }

  public func getConnectorVersion(request: GetConnectorVersionRequest) async throws
    -> GoogleCloudConnectorsV1.ConnectorVersion
  {
    try await self.getConnectorVersion(request: request, options: .init())
  }

  public func getConnectorVersion(
    request: GetConnectorVersionRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ConnectorVersion {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getConnectorVersion(
    name: Swift.String,
  ) async throws -> GoogleCloudConnectorsV1.ConnectorVersion {
    let request = GetConnectorVersionRequest().with {
      $0.name = name
    }
    return try await self.getConnectorVersion(request: request)
  }

  public func getConnectionSchemaMetadata(request: GetConnectionSchemaMetadataRequest) async throws
    -> GoogleCloudConnectorsV1.ConnectionSchemaMetadata
  {
    try await self.getConnectionSchemaMetadata(request: request, options: .init())
  }

  public func getConnectionSchemaMetadata(
    request: GetConnectionSchemaMetadataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ConnectionSchemaMetadata {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getConnectionSchemaMetadata(
    name: Swift.String,
  ) async throws -> GoogleCloudConnectorsV1.ConnectionSchemaMetadata {
    let request = GetConnectionSchemaMetadataRequest().with {
      $0.name = name
    }
    return try await self.getConnectionSchemaMetadata(request: request)
  }

  public func refreshConnectionSchemaMetadata(request: RefreshConnectionSchemaMetadataRequest)
    async throws -> GoogleLongRunning.Operation
  {
    try await self.refreshConnectionSchemaMetadata(request: request, options: .init())
  }

  public func refreshConnectionSchemaMetadata(
    request: RefreshConnectionSchemaMetadataRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func refreshConnectionSchemaMetadataPollingUntilDone(
    request: RefreshConnectionSchemaMetadataRequest
  ) async throws -> ConnectionSchemaMetadata {
    return try await self.refreshConnectionSchemaMetadataPollingUntilDone(
      request: request, options: .init())
  }

  public func refreshConnectionSchemaMetadataPollingUntilDone(
    request: RefreshConnectionSchemaMetadataRequest, options: GoogleGax.RequestOptions
  ) async throws -> ConnectionSchemaMetadata {
    throw GoogleGax.RequestError.unimplemented
  }

  public func refreshConnectionSchemaMetadataPollingUntilDone(
    name: Swift.String,
  ) async throws -> ConnectionSchemaMetadata {
    let request = RefreshConnectionSchemaMetadataRequest().with {
      $0.name = name
    }
    return try await self.refreshConnectionSchemaMetadataPollingUntilDone(request: request)
  }

  public func listRuntimeEntitySchemas(request: ListRuntimeEntitySchemasRequest) async throws
    -> GoogleCloudConnectorsV1.ListRuntimeEntitySchemasResponse
  {
    try await self.listRuntimeEntitySchemas(request: request, options: .init())
  }

  public func listRuntimeEntitySchemas(
    request: ListRuntimeEntitySchemasRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ListRuntimeEntitySchemasResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listRuntimeEntitySchemasByItems(
    request: ListRuntimeEntitySchemasRequest
  ) -> some AsyncSequence<RuntimeEntitySchema, Swift.Error> & Sendable {
    self.listRuntimeEntitySchemasByItems(request: request, options: .init())
  }

  /// List schema of a runtime entities filtered by entity name.
  ///
  /// @Snippet(path: "Connectors_ListRuntimeEntitySchemas")
  public func listRuntimeEntitySchemasByItems(
    request: ListRuntimeEntitySchemasRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<RuntimeEntitySchema, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudConnectorsV1.ListRuntimeEntitySchemasResponse in
      var request = request
      request.pageToken = token
      return try await self.listRuntimeEntitySchemas(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listRuntimeEntitySchemasByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<RuntimeEntitySchema, Swift.Error> & Sendable {
    let request = ListRuntimeEntitySchemasRequest().with {
      $0.parent = parent
    }
    return self.listRuntimeEntitySchemasByItems(request: request)
  }

  public func listRuntimeActionSchemas(request: ListRuntimeActionSchemasRequest) async throws
    -> GoogleCloudConnectorsV1.ListRuntimeActionSchemasResponse
  {
    try await self.listRuntimeActionSchemas(request: request, options: .init())
  }

  public func listRuntimeActionSchemas(
    request: ListRuntimeActionSchemasRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.ListRuntimeActionSchemasResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listRuntimeActionSchemasByItems(
    request: ListRuntimeActionSchemasRequest
  ) -> some AsyncSequence<RuntimeActionSchema, Swift.Error> & Sendable {
    self.listRuntimeActionSchemasByItems(request: request, options: .init())
  }

  /// List schema of a runtime actions filtered by action name.
  ///
  /// @Snippet(path: "Connectors_ListRuntimeActionSchemas")
  public func listRuntimeActionSchemasByItems(
    request: ListRuntimeActionSchemasRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<RuntimeActionSchema, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudConnectorsV1.ListRuntimeActionSchemasResponse in
      var request = request
      request.pageToken = token
      return try await self.listRuntimeActionSchemas(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listRuntimeActionSchemasByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<RuntimeActionSchema, Swift.Error> & Sendable {
    let request = ListRuntimeActionSchemasRequest().with {
      $0.parent = parent
    }
    return self.listRuntimeActionSchemasByItems(request: request)
  }

  public func getRuntimeConfig(request: GetRuntimeConfigRequest) async throws
    -> GoogleCloudConnectorsV1.RuntimeConfig
  {
    try await self.getRuntimeConfig(request: request, options: .init())
  }

  public func getRuntimeConfig(
    request: GetRuntimeConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.RuntimeConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getRuntimeConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudConnectorsV1.RuntimeConfig {
    let request = GetRuntimeConfigRequest().with {
      $0.name = name
    }
    return try await self.getRuntimeConfig(request: request)
  }

  public func getGlobalSettings(request: GetGlobalSettingsRequest) async throws
    -> GoogleCloudConnectorsV1.Settings
  {
    try await self.getGlobalSettings(request: request, options: .init())
  }

  public func getGlobalSettings(
    request: GetGlobalSettingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudConnectorsV1.Settings {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getGlobalSettings(
    name: Swift.String,
  ) async throws -> GoogleCloudConnectorsV1.Settings {
    let request = GetGlobalSettingsRequest().with {
      $0.name = name
    }
    return try await self.getGlobalSettings(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Connectors_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Lists operations that match the specified filter in the request. If
  /// the server doesn't support this method, it returns `UNIMPLEMENTED`.
  ///
  /// @Snippet(path: "Connectors_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
