// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// ConnectorVersion indicates a specific version of a connector.
public struct ConnectorVersion: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Resource name of the Version.
  /// Format:
  /// projects/{project}/locations/{location}/providers/{provider}/connectors/{connector}/versions/{version}
  /// Only global location is supported for Connector resource.
  public var name: Swift.String = Swift.String()

  /// Output only. Created time.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Updated time.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Resource labels to represent user-provided metadata.
  /// Refer to cloud documentation on labels for more details.
  /// https://cloud.google.com/compute/docs/labeling-resources
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Flag to mark the version indicating the launch stage.
  public var launchStage: GoogleCloudConnectorsV1.LaunchStage =
    GoogleCloudConnectorsV1.LaunchStage()

  /// Output only. ReleaseVersion of the connector, for example: "1.0.1-alpha".
  public var releaseVersion: Swift.String = Swift.String()

  /// Output only. List of auth configs supported by the Connector Version.
  public var authConfigTemplates: [AuthConfigTemplate] = []

  /// Output only. List of config variables needed to create a connection.
  public var configVariableTemplates: [ConfigVariableTemplate] = []

  /// Output only. Information about the runtime features supported by the
  /// Connector.
  public var supportedRuntimeFeatures: SupportedRuntimeFeatures? = nil

  /// Output only. Display name.
  public var displayName: Swift.String = Swift.String()

  /// Output only. Configuration for Egress Control.
  public var egressControlConfig: EgressControlConfig? = nil

  /// Output only. Role grant configurations for this connector version.
  public var roleGrants: [RoleGrant] = []

  /// Output only. Role grant configuration for this config variable. It will be
  /// DEPRECATED soon.
  public var roleGrant: RoleGrant? = nil

  /// Output only. Ssl configuration supported by the Connector.
  public var sslConfigTemplate: SslConfigTemplate? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ConnectorVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConnectorVersion().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let launchStage = CodingKeys(stringValue: "launchStage")
    static let releaseVersion = CodingKeys(stringValue: "releaseVersion")
    static let authConfigTemplates = CodingKeys(stringValue: "authConfigTemplates")
    static let configVariableTemplates = CodingKeys(stringValue: "configVariableTemplates")
    static let supportedRuntimeFeatures = CodingKeys(stringValue: "supportedRuntimeFeatures")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let egressControlConfig = CodingKeys(stringValue: "egressControlConfig")
    static let roleGrants = CodingKeys(stringValue: "roleGrants")
    static let roleGrant = CodingKeys(stringValue: "roleGrant")
    static let sslConfigTemplate = CodingKeys(stringValue: "sslConfigTemplate")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "launchStage",
      "releaseVersion",
      "authConfigTemplates",
      "configVariableTemplates",
      "supportedRuntimeFeatures",
      "displayName",
      "egressControlConfig",
      "roleGrants",
      "roleGrant",
      "sslConfigTemplate",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(
      GoogleCloudConnectorsV1.LaunchStage.self, forKey: .launchStage)
    {
      self.launchStage = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .releaseVersion) {
      self.releaseVersion = value
    }
    if let value = try container.decodeIfPresent(
      [AuthConfigTemplate].self, forKey: .authConfigTemplates)
    {
      self.authConfigTemplates = value
    }
    if let value = try container.decodeIfPresent(
      [ConfigVariableTemplate].self, forKey: .configVariableTemplates)
    {
      self.configVariableTemplates = value
    }
    self.supportedRuntimeFeatures = try container.decodeIfPresent(
      SupportedRuntimeFeatures.self, forKey: .supportedRuntimeFeatures)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    self.egressControlConfig = try container.decodeIfPresent(
      EgressControlConfig.self, forKey: .egressControlConfig)
    if let value = try container.decodeIfPresent([RoleGrant].self, forKey: .roleGrants) {
      self.roleGrants = value
    }
    self.roleGrant = try container.decodeIfPresent(RoleGrant.self, forKey: .roleGrant)
    self.sslConfigTemplate = try container.decodeIfPresent(
      SslConfigTemplate.self, forKey: .sslConfigTemplate)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.launchStage, forKey: .launchStage)
    try container.encode(self.releaseVersion, forKey: .releaseVersion)
    try container.encode(self.authConfigTemplates, forKey: .authConfigTemplates)
    try container.encode(self.configVariableTemplates, forKey: .configVariableTemplates)
    try container.encodeIfPresent(self.supportedRuntimeFeatures, forKey: .supportedRuntimeFeatures)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encodeIfPresent(self.egressControlConfig, forKey: .egressControlConfig)
    try container.encode(self.roleGrants, forKey: .roleGrants)
    try container.encodeIfPresent(self.roleGrant, forKey: .roleGrant)
    try container.encodeIfPresent(self.sslConfigTemplate, forKey: .sslConfigTemplate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ConnectorVersion`: `"type.googleapis.com/google.cloud.connectors.v1.ConnectorVersion"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.ConnectorVersion"
  }

  /// Initialize an instance of `ConnectorVersion` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.connectors.v1.ConnectorVersion"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ConnectorVersion` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
