// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// All possible data types of a entity or action field.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum DataType: Codable, Equatable, Hashable, Sendable {
  /// Data type is not specified.
  case unspecified
  /// DEPRECATED! Use DATA_TYPE_INTEGER.
  @available(*, deprecated)
  case int
  /// Short integer(int16) data type.
  case smallint
  /// Double data type.
  case double
  /// Date data type.
  case date
  /// DEPRECATED! Use DATA_TYPE_TIMESTAMP.
  @available(*, deprecated)
  case datetime
  /// Time data type.
  case time
  /// DEPRECATED! Use DATA_TYPE_VARCHAR.
  @available(*, deprecated)
  case string
  /// DEPRECATED! Use DATA_TYPE_BIGINT.
  @available(*, deprecated)
  case long
  /// Boolean data type.
  case boolean
  /// Decimal data type.
  case decimal
  /// DEPRECATED! Use DATA_TYPE_VARCHAR.
  @available(*, deprecated)
  case uuid
  /// UNSUPPORTED! Binary data type.
  case blob
  /// Bit data type.
  case bit
  /// Small integer(int8) data type.
  case tinyint
  /// Integer(int32) data type.
  case integer
  /// Long integer(int64) data type.
  case bigint
  /// Float data type.
  case float
  /// Real data type.
  case real
  /// Numeric data type.
  case numeric
  /// Char data type.
  case char
  /// Varchar data type.
  case varchar
  /// Longvarchar data type.
  case longvarchar
  /// Timestamp data type.
  case timestamp
  /// Nchar data type.
  case nchar
  /// Nvarchar data type.
  case nvarchar
  /// Longnvarchar data type.
  case longnvarchar
  /// Null data type.
  case null
  /// UNSUPPORTED! Binary data type.
  case other
  /// UNSUPPORTED! Binary data type.
  case javaObject
  /// UNSUPPORTED! Binary data type.
  case distinct
  /// UNSUPPORTED! Binary data type.
  case `struct`
  /// UNSUPPORTED! Binary data type.
  case array
  /// UNSUPPORTED! Binary data type.
  case clob
  /// UNSUPPORTED! Binary data type.
  case ref
  /// UNSUPPORTED! Binary data type.
  case datalink
  /// UNSUPPORTED! Row id data type.
  case rowid
  /// UNSUPPORTED! Binary data type.
  case binary
  /// UNSUPPORTED! Variable binary data type.
  case varbinary
  /// UNSUPPORTED! Long variable binary data type.
  case longvarbinary
  /// UNSUPPORTED! NCLOB data type.
  case nclob
  /// UNSUPPORTED! SQL XML data type is not supported.
  case sqlxml
  /// UNSUPPORTED! Cursor reference type is not supported.
  case refCursor
  /// UNSUPPORTED! Use TIME or TIMESTAMP instead.
  case timeWithTimezone
  /// UNSUPPORTED! Use TIMESTAMP instead.
  case timestampWithTimezone
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .int: return 1
    case .smallint: return 2
    case .double: return 3
    case .date: return 4
    case .datetime: return 5
    case .time: return 6
    case .string: return 7
    case .long: return 8
    case .boolean: return 9
    case .decimal: return 10
    case .uuid: return 11
    case .blob: return 12
    case .bit: return 13
    case .tinyint: return 14
    case .integer: return 15
    case .bigint: return 16
    case .float: return 17
    case .real: return 18
    case .numeric: return 19
    case .char: return 20
    case .varchar: return 21
    case .longvarchar: return 22
    case .timestamp: return 23
    case .nchar: return 24
    case .nvarchar: return 25
    case .longnvarchar: return 26
    case .null: return 27
    case .other: return 28
    case .javaObject: return 29
    case .distinct: return 30
    case .`struct`: return 31
    case .array: return 32
    case .clob: return 33
    case .ref: return 34
    case .datalink: return 35
    case .rowid: return 36
    case .binary: return 37
    case .varbinary: return 38
    case .longvarbinary: return 39
    case .nclob: return 40
    case .sqlxml: return 41
    case .refCursor: return 42
    case .timeWithTimezone: return 43
    case .timestampWithTimezone: return 44
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "DATA_TYPE_UNSPECIFIED"
    case .int: return "DATA_TYPE_INT"
    case .smallint: return "DATA_TYPE_SMALLINT"
    case .double: return "DATA_TYPE_DOUBLE"
    case .date: return "DATA_TYPE_DATE"
    case .datetime: return "DATA_TYPE_DATETIME"
    case .time: return "DATA_TYPE_TIME"
    case .string: return "DATA_TYPE_STRING"
    case .long: return "DATA_TYPE_LONG"
    case .boolean: return "DATA_TYPE_BOOLEAN"
    case .decimal: return "DATA_TYPE_DECIMAL"
    case .uuid: return "DATA_TYPE_UUID"
    case .blob: return "DATA_TYPE_BLOB"
    case .bit: return "DATA_TYPE_BIT"
    case .tinyint: return "DATA_TYPE_TINYINT"
    case .integer: return "DATA_TYPE_INTEGER"
    case .bigint: return "DATA_TYPE_BIGINT"
    case .float: return "DATA_TYPE_FLOAT"
    case .real: return "DATA_TYPE_REAL"
    case .numeric: return "DATA_TYPE_NUMERIC"
    case .char: return "DATA_TYPE_CHAR"
    case .varchar: return "DATA_TYPE_VARCHAR"
    case .longvarchar: return "DATA_TYPE_LONGVARCHAR"
    case .timestamp: return "DATA_TYPE_TIMESTAMP"
    case .nchar: return "DATA_TYPE_NCHAR"
    case .nvarchar: return "DATA_TYPE_NVARCHAR"
    case .longnvarchar: return "DATA_TYPE_LONGNVARCHAR"
    case .null: return "DATA_TYPE_NULL"
    case .other: return "DATA_TYPE_OTHER"
    case .javaObject: return "DATA_TYPE_JAVA_OBJECT"
    case .distinct: return "DATA_TYPE_DISTINCT"
    case .`struct`: return "DATA_TYPE_STRUCT"
    case .array: return "DATA_TYPE_ARRAY"
    case .clob: return "DATA_TYPE_CLOB"
    case .ref: return "DATA_TYPE_REF"
    case .datalink: return "DATA_TYPE_DATALINK"
    case .rowid: return "DATA_TYPE_ROWID"
    case .binary: return "DATA_TYPE_BINARY"
    case .varbinary: return "DATA_TYPE_VARBINARY"
    case .longvarbinary: return "DATA_TYPE_LONGVARBINARY"
    case .nclob: return "DATA_TYPE_NCLOB"
    case .sqlxml: return "DATA_TYPE_SQLXML"
    case .refCursor: return "DATA_TYPE_REF_CURSOR"
    case .timeWithTimezone: return "DATA_TYPE_TIME_WITH_TIMEZONE"
    case .timestampWithTimezone: return "DATA_TYPE_TIMESTAMP_WITH_TIMEZONE"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DataType/unknownStringValue(_:)).
  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "DATA_TYPE_UNSPECIFIED": self = .unspecified
    case "DATA_TYPE_INT": self = .int
    case "DATA_TYPE_SMALLINT": self = .smallint
    case "DATA_TYPE_DOUBLE": self = .double
    case "DATA_TYPE_DATE": self = .date
    case "DATA_TYPE_DATETIME": self = .datetime
    case "DATA_TYPE_TIME": self = .time
    case "DATA_TYPE_STRING": self = .string
    case "DATA_TYPE_LONG": self = .long
    case "DATA_TYPE_BOOLEAN": self = .boolean
    case "DATA_TYPE_DECIMAL": self = .decimal
    case "DATA_TYPE_UUID": self = .uuid
    case "DATA_TYPE_BLOB": self = .blob
    case "DATA_TYPE_BIT": self = .bit
    case "DATA_TYPE_TINYINT": self = .tinyint
    case "DATA_TYPE_INTEGER": self = .integer
    case "DATA_TYPE_BIGINT": self = .bigint
    case "DATA_TYPE_FLOAT": self = .float
    case "DATA_TYPE_REAL": self = .real
    case "DATA_TYPE_NUMERIC": self = .numeric
    case "DATA_TYPE_CHAR": self = .char
    case "DATA_TYPE_VARCHAR": self = .varchar
    case "DATA_TYPE_LONGVARCHAR": self = .longvarchar
    case "DATA_TYPE_TIMESTAMP": self = .timestamp
    case "DATA_TYPE_NCHAR": self = .nchar
    case "DATA_TYPE_NVARCHAR": self = .nvarchar
    case "DATA_TYPE_LONGNVARCHAR": self = .longnvarchar
    case "DATA_TYPE_NULL": self = .null
    case "DATA_TYPE_OTHER": self = .other
    case "DATA_TYPE_JAVA_OBJECT": self = .javaObject
    case "DATA_TYPE_DISTINCT": self = .distinct
    case "DATA_TYPE_STRUCT": self = .`struct`
    case "DATA_TYPE_ARRAY": self = .array
    case "DATA_TYPE_CLOB": self = .clob
    case "DATA_TYPE_REF": self = .ref
    case "DATA_TYPE_DATALINK": self = .datalink
    case "DATA_TYPE_ROWID": self = .rowid
    case "DATA_TYPE_BINARY": self = .binary
    case "DATA_TYPE_VARBINARY": self = .varbinary
    case "DATA_TYPE_LONGVARBINARY": self = .longvarbinary
    case "DATA_TYPE_NCLOB": self = .nclob
    case "DATA_TYPE_SQLXML": self = .sqlxml
    case "DATA_TYPE_REF_CURSOR": self = .refCursor
    case "DATA_TYPE_TIME_WITH_TIMEZONE": self = .timeWithTimezone
    case "DATA_TYPE_TIMESTAMP_WITH_TIMEZONE": self = .timestampWithTimezone
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DataType/unknownIntValue(_:)).
  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .int
    case 2: self = .smallint
    case 3: self = .double
    case 4: self = .date
    case 5: self = .datetime
    case 6: self = .time
    case 7: self = .string
    case 8: self = .long
    case 9: self = .boolean
    case 10: self = .decimal
    case 11: self = .uuid
    case 12: self = .blob
    case 13: self = .bit
    case 14: self = .tinyint
    case 15: self = .integer
    case 16: self = .bigint
    case 17: self = .float
    case 18: self = .real
    case 19: self = .numeric
    case 20: self = .char
    case 21: self = .varchar
    case 22: self = .longvarchar
    case 23: self = .timestamp
    case 24: self = .nchar
    case 25: self = .nvarchar
    case 26: self = .longnvarchar
    case 27: self = .null
    case 28: self = .other
    case 29: self = .javaObject
    case 30: self = .distinct
    case 31: self = .`struct`
    case 32: self = .array
    case 33: self = .clob
    case 34: self = .ref
    case 35: self = .datalink
    case 36: self = .rowid
    case 37: self = .binary
    case 38: self = .varbinary
    case 39: self = .longvarbinary
    case 40: self = .nclob
    case 41: self = .sqlxml
    case 42: self = .refCursor
    case 43: self = .timeWithTimezone
    case 44: self = .timestampWithTimezone
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("DATA_TYPE_UNSPECIFIED")
    case .int: return try container.encode("DATA_TYPE_INT")
    case .smallint: return try container.encode("DATA_TYPE_SMALLINT")
    case .double: return try container.encode("DATA_TYPE_DOUBLE")
    case .date: return try container.encode("DATA_TYPE_DATE")
    case .datetime: return try container.encode("DATA_TYPE_DATETIME")
    case .time: return try container.encode("DATA_TYPE_TIME")
    case .string: return try container.encode("DATA_TYPE_STRING")
    case .long: return try container.encode("DATA_TYPE_LONG")
    case .boolean: return try container.encode("DATA_TYPE_BOOLEAN")
    case .decimal: return try container.encode("DATA_TYPE_DECIMAL")
    case .uuid: return try container.encode("DATA_TYPE_UUID")
    case .blob: return try container.encode("DATA_TYPE_BLOB")
    case .bit: return try container.encode("DATA_TYPE_BIT")
    case .tinyint: return try container.encode("DATA_TYPE_TINYINT")
    case .integer: return try container.encode("DATA_TYPE_INTEGER")
    case .bigint: return try container.encode("DATA_TYPE_BIGINT")
    case .float: return try container.encode("DATA_TYPE_FLOAT")
    case .real: return try container.encode("DATA_TYPE_REAL")
    case .numeric: return try container.encode("DATA_TYPE_NUMERIC")
    case .char: return try container.encode("DATA_TYPE_CHAR")
    case .varchar: return try container.encode("DATA_TYPE_VARCHAR")
    case .longvarchar: return try container.encode("DATA_TYPE_LONGVARCHAR")
    case .timestamp: return try container.encode("DATA_TYPE_TIMESTAMP")
    case .nchar: return try container.encode("DATA_TYPE_NCHAR")
    case .nvarchar: return try container.encode("DATA_TYPE_NVARCHAR")
    case .longnvarchar: return try container.encode("DATA_TYPE_LONGNVARCHAR")
    case .null: return try container.encode("DATA_TYPE_NULL")
    case .other: return try container.encode("DATA_TYPE_OTHER")
    case .javaObject: return try container.encode("DATA_TYPE_JAVA_OBJECT")
    case .distinct: return try container.encode("DATA_TYPE_DISTINCT")
    case .`struct`: return try container.encode("DATA_TYPE_STRUCT")
    case .array: return try container.encode("DATA_TYPE_ARRAY")
    case .clob: return try container.encode("DATA_TYPE_CLOB")
    case .ref: return try container.encode("DATA_TYPE_REF")
    case .datalink: return try container.encode("DATA_TYPE_DATALINK")
    case .rowid: return try container.encode("DATA_TYPE_ROWID")
    case .binary: return try container.encode("DATA_TYPE_BINARY")
    case .varbinary: return try container.encode("DATA_TYPE_VARBINARY")
    case .longvarbinary: return try container.encode("DATA_TYPE_LONGVARBINARY")
    case .nclob: return try container.encode("DATA_TYPE_NCLOB")
    case .sqlxml: return try container.encode("DATA_TYPE_SQLXML")
    case .refCursor: return try container.encode("DATA_TYPE_REF_CURSOR")
    case .timeWithTimezone: return try container.encode("DATA_TYPE_TIME_WITH_TIMEZONE")
    case .timestampWithTimezone: return try container.encode("DATA_TYPE_TIMESTAMP_WITH_TIMEZONE")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
