// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

public struct Destination: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The port is the target port number that is accepted by the destination.
  public var port: Swift.Int32 = Swift.Int32()

  public var destination: DestinationOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Destination`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Destination().with { $0.serviceAttachment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let serviceAttachment = CodingKeys(stringValue: "serviceAttachment")
    static let host = CodingKeys(stringValue: "host")
    static let port = CodingKeys(stringValue: "port")

    static let _knownKeys: Set<Swift.String> = [
      "serviceAttachment",
      "host",
      "port",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .port) {
      self.port = value
    }

    var destination: DestinationOneOf? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let serviceAttachment = try container.decodeIfPresent(
      Swift.String.self, forKey: .serviceAttachment)
    {
      try destinationCheckAndSet(.serviceAttachment(serviceAttachment))
    }
    if let host = try container.decodeIfPresent(Swift.String.self, forKey: .host) {
      try destinationCheckAndSet(.host(host))
    }
    self.destination = destination
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.port, forKey: .port)

    if let choice = self.destination {
      switch choice {
      case .serviceAttachment(let value):
        try container.encode(value, forKey: .serviceAttachment)
      case .host(let value):
        try container.encode(value, forKey: .host)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum DestinationOneOf: Codable, Equatable, Sendable {
    /// PSC service attachments.
    /// Format: projects/*/regions/*/serviceAttachments/*
    case serviceAttachment(Swift.String)
    /// For publicly routable host.
    case host(Swift.String)
  }

  /// The type URL for `Destination`: `"type.googleapis.com/google.cloud.connectors.v1.Destination"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.Destination"
  }

  /// Initialize an instance of `Destination` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.connectors.v1.Destination"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Destination` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
