// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// This configuration defines all the Cloud IAM roles that needs to be granted
/// to a particular GCP resource for the selected prinicpal like service
/// account. These configurations will let UI display to customers what
/// IAM roles need to be granted by them. Or these configurations can be used
/// by the UI to render a 'grant' button to do the same on behalf of the user.
public struct RoleGrant: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Prinicipal/Identity for whom the role need to assigned.
  public var principal: RoleGrant.Principal = RoleGrant.Principal()

  /// List of roles that need to be granted.
  public var roles: [Swift.String] = []

  /// Resource on which the roles needs to be granted for the principal.
  public var resource: RoleGrant.Resource? = nil

  /// Template that UI can use to provide helper text to customers.
  public var helperTextTemplate: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RoleGrant`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RoleGrant().with { $0.principal = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let principal = CodingKeys(stringValue: "principal")
    static let roles = CodingKeys(stringValue: "roles")
    static let resource = CodingKeys(stringValue: "resource")
    static let helperTextTemplate = CodingKeys(stringValue: "helperTextTemplate")

    static let _knownKeys: Set<Swift.String> = [
      "principal",
      "roles",
      "resource",
      "helperTextTemplate",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(RoleGrant.Principal.self, forKey: .principal) {
      self.principal = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .roles) {
      self.roles = value
    }
    self.resource = try container.decodeIfPresent(RoleGrant.Resource.self, forKey: .resource)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .helperTextTemplate) {
      self.helperTextTemplate = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.principal, forKey: .principal)
    try container.encode(self.roles, forKey: .roles)
    try container.encodeIfPresent(self.resource, forKey: .resource)
    try container.encode(self.helperTextTemplate, forKey: .helperTextTemplate)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Resource definition
  public struct Resource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Different types of resource supported.
    public var type: RoleGrant.Resource.Type_ = RoleGrant.Resource.Type_()

    /// Template to uniquely represent a GCP resource in a format IAM expects
    /// This is a template that can have references to other values provided in
    /// the config variable template.
    public var pathTemplate: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Resource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Resource().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let type = CodingKeys(stringValue: "type")
      static let pathTemplate = CodingKeys(stringValue: "pathTemplate")

      static let _knownKeys: Set<Swift.String> = [
        "type",
        "pathTemplate",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(RoleGrant.Resource.Type_.self, forKey: .type) {
        self.type = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pathTemplate) {
        self.pathTemplate = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.type, forKey: .type)
      try container.encode(self.pathTemplate, forKey: .pathTemplate)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Resource Type definition.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum Type_: Codable, Equatable, Hashable, Sendable {
      /// Value type is not specified.
      case unspecified
      /// GCP Project Resource.
      case gcpProject
      /// Any GCP Resource which is identified uniquely by IAM.
      case gcpResource
      /// GCP Secret Resource.
      case gcpSecretmanagerSecret
      /// GCP Secret Version Resource.
      case gcpSecretmanagerSecretVersion
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .gcpProject: return 1
        case .gcpResource: return 2
        case .gcpSecretmanagerSecret: return 3
        case .gcpSecretmanagerSecretVersion: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TYPE_UNSPECIFIED"
        case .gcpProject: return "GCP_PROJECT"
        case .gcpResource: return "GCP_RESOURCE"
        case .gcpSecretmanagerSecret: return "GCP_SECRETMANAGER_SECRET"
        case .gcpSecretmanagerSecretVersion: return "GCP_SECRETMANAGER_SECRET_VERSION"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TYPE_UNSPECIFIED": self = .unspecified
        case "GCP_PROJECT": self = .gcpProject
        case "GCP_RESOURCE": self = .gcpResource
        case "GCP_SECRETMANAGER_SECRET": self = .gcpSecretmanagerSecret
        case "GCP_SECRETMANAGER_SECRET_VERSION": self = .gcpSecretmanagerSecretVersion
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .gcpProject
        case 2: self = .gcpResource
        case 3: self = .gcpSecretmanagerSecret
        case 4: self = .gcpSecretmanagerSecretVersion
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
        case .gcpProject: return try container.encode("GCP_PROJECT")
        case .gcpResource: return try container.encode("GCP_RESOURCE")
        case .gcpSecretmanagerSecret: return try container.encode("GCP_SECRETMANAGER_SECRET")
        case .gcpSecretmanagerSecretVersion:
          return try container.encode("GCP_SECRETMANAGER_SECRET_VERSION")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The type URL for `Resource`: `"type.googleapis.com/google.cloud.connectors.v1.RoleGrant.Resource"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.RoleGrant.Resource"
    }

    /// Initialize an instance of `Resource` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.connectors.v1.RoleGrant.Resource"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Resource` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Supported Principal values.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Principal: Codable, Equatable, Hashable, Sendable {
    /// Value type is not specified.
    case unspecified
    /// Service Account used for Connector workload identity
    /// This is either the default service account if unspecified or Service
    /// Account provided by Customers through BYOSA.
    case connectorSa
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .connectorSa: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PRINCIPAL_UNSPECIFIED"
      case .connectorSa: return "CONNECTOR_SA"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Principal/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PRINCIPAL_UNSPECIFIED": self = .unspecified
      case "CONNECTOR_SA": self = .connectorSa
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Principal/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .connectorSa
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PRINCIPAL_UNSPECIFIED")
      case .connectorSa: return try container.encode("CONNECTOR_SA")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `RoleGrant`: `"type.googleapis.com/google.cloud.connectors.v1.RoleGrant"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.RoleGrant"
  }

  /// Initialize an instance of `RoleGrant` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.connectors.v1.RoleGrant"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `RoleGrant` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
