// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Schema of a runtime entity.
public struct RuntimeEntitySchema: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Name of the entity.
  public var entity: Swift.String = Swift.String()

  /// Output only. List of fields in the entity.
  public var fields: [RuntimeEntitySchema.Field] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RuntimeEntitySchema`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuntimeEntitySchema().with { $0.entity = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let entity = CodingKeys(stringValue: "entity")
    static let fields = CodingKeys(stringValue: "fields")

    static let _knownKeys: Set<Swift.String> = [
      "entity",
      "fields",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .entity) {
      self.entity = value
    }
    if let value = try container.decodeIfPresent([RuntimeEntitySchema.Field].self, forKey: .fields)
    {
      self.fields = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.entity, forKey: .entity)
    try container.encode(self.fields, forKey: .fields)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Metadata of an entity field.
  public struct Field: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Name of the Field.
    public var field: Swift.String = Swift.String()

    /// A brief description of the Field.
    public var description: Swift.String = Swift.String()

    /// The data type of the Field.
    public var dataType: DataType = DataType()

    /// The following boolean field specifies if the current Field acts
    /// as a primary key or id if the parent is of type entity.
    public var key: Swift.Bool = Swift.Bool()

    /// Specifies if the Field is readonly.
    public var readonly: Swift.Bool = Swift.Bool()

    /// Specifies whether a null value is allowed.
    public var nullable: Swift.Bool = Swift.Bool()

    /// The following field specifies the default value of the Field provided
    /// by the external system if a value is not provided.
    public var defaultValue: GoogleWKT.WKTValue? = nil

    /// The following map contains fields that are not explicitly mentioned
    /// above,this give connectors the flexibility to add new metadata
    /// fields.
    public var additionalDetails: GoogleWKT.WKTStruct? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Field`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Field().with { $0.field = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let field = CodingKeys(stringValue: "field")
      static let description = CodingKeys(stringValue: "description")
      static let dataType = CodingKeys(stringValue: "dataType")
      static let key = CodingKeys(stringValue: "key")
      static let readonly = CodingKeys(stringValue: "readonly")
      static let nullable = CodingKeys(stringValue: "nullable")
      static let defaultValue = CodingKeys(stringValue: "defaultValue")
      static let additionalDetails = CodingKeys(stringValue: "additionalDetails")

      static let _knownKeys: Set<Swift.String> = [
        "field",
        "description",
        "dataType",
        "key",
        "readonly",
        "nullable",
        "defaultValue",
        "additionalDetails",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .field) {
        self.field = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      if let value = try container.decodeIfPresent(DataType.self, forKey: .dataType) {
        self.dataType = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .key) {
        self.key = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .readonly) {
        self.readonly = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .nullable) {
        self.nullable = value
      }
      self.defaultValue = try container.decodeIfPresent(
        GoogleWKT.WKTValue.self, forKey: .defaultValue)
      self.additionalDetails = try container.decodeIfPresent(
        GoogleWKT.WKTStruct.self, forKey: .additionalDetails)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.field, forKey: .field)
      try container.encode(self.description, forKey: .description)
      try container.encode(self.dataType, forKey: .dataType)
      try container.encode(self.key, forKey: .key)
      try container.encode(self.readonly, forKey: .readonly)
      try container.encode(self.nullable, forKey: .nullable)
      try container.encodeIfPresent(self.defaultValue, forKey: .defaultValue)
      try container.encodeIfPresent(self.additionalDetails, forKey: .additionalDetails)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `Field`: `"type.googleapis.com/google.cloud.connectors.v1.RuntimeEntitySchema.Field"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.RuntimeEntitySchema.Field"
    }

    /// Initialize an instance of `Field` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.connectors.v1.RuntimeEntitySchema.Field"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `Field` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `RuntimeEntitySchema`: `"type.googleapis.com/google.cloud.connectors.v1.RuntimeEntitySchema"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.RuntimeEntitySchema"
  }

  /// Initialize an instance of `RuntimeEntitySchema` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.connectors.v1.RuntimeEntitySchema"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `RuntimeEntitySchema` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
