// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Schema of a runtime action.
public struct RuntimeActionSchema: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Name of the action.
  public var action: Swift.String = Swift.String()

  /// Output only. List of input parameter metadata for the action.
  public var inputParameters: [RuntimeActionSchema.InputParameter] = []

  /// Output only. List of result field metadata.
  public var resultMetadata: [RuntimeActionSchema.ResultMetadata] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RuntimeActionSchema`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuntimeActionSchema().with { $0.action = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let action = CodingKeys(stringValue: "action")
    static let inputParameters = CodingKeys(stringValue: "inputParameters")
    static let resultMetadata = CodingKeys(stringValue: "resultMetadata")

    static let _knownKeys: Set<Swift.String> = [
      "action",
      "inputParameters",
      "resultMetadata",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .action) {
      self.action = value
    }
    if let value = try container.decodeIfPresent(
      [RuntimeActionSchema.InputParameter].self, forKey: .inputParameters)
    {
      self.inputParameters = value
    }
    if let value = try container.decodeIfPresent(
      [RuntimeActionSchema.ResultMetadata].self, forKey: .resultMetadata)
    {
      self.resultMetadata = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.action, forKey: .action)
    try container.encode(self.inputParameters, forKey: .inputParameters)
    try container.encode(self.resultMetadata, forKey: .resultMetadata)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Metadata of an input parameter.
  public struct InputParameter: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Name of the Parameter.
    public var parameter: Swift.String = Swift.String()

    /// A brief description of the Parameter.
    public var description: Swift.String = Swift.String()

    /// The data type of the Parameter.
    public var dataType: DataType = DataType()

    /// Specifies whether a null value is allowed.
    public var nullable: Swift.Bool = Swift.Bool()

    /// The following field specifies the default value of the Parameter
    /// provided by the external system if a value is not provided.
    public var defaultValue: GoogleWKT.WKTValue? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InputParameter`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InputParameter().with { $0.parameter = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let parameter = CodingKeys(stringValue: "parameter")
      static let description = CodingKeys(stringValue: "description")
      static let dataType = CodingKeys(stringValue: "dataType")
      static let nullable = CodingKeys(stringValue: "nullable")
      static let defaultValue = CodingKeys(stringValue: "defaultValue")

      static let _knownKeys: Set<Swift.String> = [
        "parameter",
        "description",
        "dataType",
        "nullable",
        "defaultValue",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parameter) {
        self.parameter = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      if let value = try container.decodeIfPresent(DataType.self, forKey: .dataType) {
        self.dataType = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .nullable) {
        self.nullable = value
      }
      self.defaultValue = try container.decodeIfPresent(
        GoogleWKT.WKTValue.self, forKey: .defaultValue)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.parameter, forKey: .parameter)
      try container.encode(self.description, forKey: .description)
      try container.encode(self.dataType, forKey: .dataType)
      try container.encode(self.nullable, forKey: .nullable)
      try container.encodeIfPresent(self.defaultValue, forKey: .defaultValue)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.RuntimeActionSchema.InputParameter"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Metadata of result field.
  public struct ResultMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Name of the result field.
    public var field: Swift.String = Swift.String()

    /// A brief description of the field.
    public var description: Swift.String = Swift.String()

    /// The data type of the field.
    public var dataType: DataType = DataType()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ResultMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResultMetadata().with { $0.field = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let field = CodingKeys(stringValue: "field")
      static let description = CodingKeys(stringValue: "description")
      static let dataType = CodingKeys(stringValue: "dataType")

      static let _knownKeys: Set<Swift.String> = [
        "field",
        "description",
        "dataType",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .field) {
        self.field = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      if let value = try container.decodeIfPresent(DataType.self, forKey: .dataType) {
        self.dataType = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.field, forKey: .field)
      try container.encode(self.description, forKey: .description)
      try container.encode(self.dataType, forKey: .dataType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.connectors.v1.RuntimeActionSchema.ResultMetadata"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.RuntimeActionSchema"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
