// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// SSL Configuration of a connection
public struct SslConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Controls the ssl type for the given connector version.
  public var type: SslType = SslType()

  /// Trust Model of the SSL connection
  public var trustModel: SslConfig.TrustModel = SslConfig.TrustModel()

  /// Private Server Certificate. Needs to be specified if trust model is
  /// `PRIVATE`.
  public var privateServerCertificate: Secret? = nil

  /// Client Certificate
  public var clientCertificate: Secret? = nil

  /// Client Private Key
  public var clientPrivateKey: Secret? = nil

  /// Secret containing the passphrase protecting the Client Private Key
  public var clientPrivateKeyPass: Secret? = nil

  /// Type of Server Cert (PEM/JKS/.. etc.)
  public var serverCertType: CertType = CertType()

  /// Type of Client Cert (PEM/JKS/.. etc.)
  public var clientCertType: CertType = CertType()

  /// Bool for enabling SSL
  public var useSsl: Swift.Bool = Swift.Bool()

  /// Additional SSL related field values
  public var additionalVariables: [ConfigVariable] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SslConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SslConfig().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let type = CodingKeys(stringValue: "type")
    static let trustModel = CodingKeys(stringValue: "trustModel")
    static let privateServerCertificate = CodingKeys(stringValue: "privateServerCertificate")
    static let clientCertificate = CodingKeys(stringValue: "clientCertificate")
    static let clientPrivateKey = CodingKeys(stringValue: "clientPrivateKey")
    static let clientPrivateKeyPass = CodingKeys(stringValue: "clientPrivateKeyPass")
    static let serverCertType = CodingKeys(stringValue: "serverCertType")
    static let clientCertType = CodingKeys(stringValue: "clientCertType")
    static let useSsl = CodingKeys(stringValue: "useSsl")
    static let additionalVariables = CodingKeys(stringValue: "additionalVariables")

    static let _knownKeys: Set<Swift.String> = [
      "type",
      "trustModel",
      "privateServerCertificate",
      "clientCertificate",
      "clientPrivateKey",
      "clientPrivateKeyPass",
      "serverCertType",
      "clientCertType",
      "useSsl",
      "additionalVariables",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(SslType.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(SslConfig.TrustModel.self, forKey: .trustModel) {
      self.trustModel = value
    }
    self.privateServerCertificate = try container.decodeIfPresent(
      Secret.self, forKey: .privateServerCertificate)
    self.clientCertificate = try container.decodeIfPresent(Secret.self, forKey: .clientCertificate)
    self.clientPrivateKey = try container.decodeIfPresent(Secret.self, forKey: .clientPrivateKey)
    self.clientPrivateKeyPass = try container.decodeIfPresent(
      Secret.self, forKey: .clientPrivateKeyPass)
    if let value = try container.decodeIfPresent(CertType.self, forKey: .serverCertType) {
      self.serverCertType = value
    }
    if let value = try container.decodeIfPresent(CertType.self, forKey: .clientCertType) {
      self.clientCertType = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .useSsl) {
      self.useSsl = value
    }
    if let value = try container.decodeIfPresent(
      [ConfigVariable].self, forKey: .additionalVariables)
    {
      self.additionalVariables = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.trustModel, forKey: .trustModel)
    try container.encodeIfPresent(self.privateServerCertificate, forKey: .privateServerCertificate)
    try container.encodeIfPresent(self.clientCertificate, forKey: .clientCertificate)
    try container.encodeIfPresent(self.clientPrivateKey, forKey: .clientPrivateKey)
    try container.encodeIfPresent(self.clientPrivateKeyPass, forKey: .clientPrivateKeyPass)
    try container.encode(self.serverCertType, forKey: .serverCertType)
    try container.encode(self.clientCertType, forKey: .clientCertType)
    try container.encode(self.useSsl, forKey: .useSsl)
    try container.encode(self.additionalVariables, forKey: .additionalVariables)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Enum for Ttust Model
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum TrustModel: Codable, Equatable, Hashable, Sendable {
    /// Public Trust Model. Takes the Default Java trust store.
    case `public`
    /// Private Trust Model. Takes custom/private trust store.
    case `private`
    /// Insecure Trust Model. Accept all certificates.
    case insecure
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .`public`
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .`public`: return 0
      case .`private`: return 1
      case .insecure: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .`public`: return "PUBLIC"
      case .`private`: return "PRIVATE"
      case .insecure: return "INSECURE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TrustModel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PUBLIC": self = .`public`
      case "PRIVATE": self = .`private`
      case "INSECURE": self = .insecure
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TrustModel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .`public`
      case 1: self = .`private`
      case 2: self = .insecure
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .`public`: return try container.encode("PUBLIC")
      case .`private`: return try container.encode("PRIVATE")
      case .insecure: return try container.encode("INSECURE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.connectors.v1.SslConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
